Tree node change
holmgr/dsa-cozy-corner pull request #13
Opened 2017-03-29 19:24 UTC by fumoffu947

This is for the convenience of setting children on positions when the list of children is not that long. Like when a binary tree node chould only have a right child but not a left child.

2017-04-07 11:12 UTC, holmgr requested changes
Just a minor nickpick before I approve :)

2017-04-07 11:12 UTC, holmgr commented on src/tree_node.h
> +  // larger then the size of the vector.
Would personally like a multiline comment instead (/* */) since it is multiple lines.

2017-04-12 04:40 UTC, alexsaaf requested changes
The changes look good, not sure why all the old commits are in the pull request, have they not already been merged? Had one minor request about a comment.

2017-04-12 04:40 UTC, alexsaaf commented on src/tree_node.h
> +		// I calculate how many empty spaces to add to the list of children.
Would like to have "// Calculates ... " instead of "// I calculate" as it describes what the code does, not what you are doing.

2017-04-26 05:22 UTC, fumoffu947 commented
All the problems that was identified have been fixed.

2017-04-26 14:18 UTC, holmgr approved these changes
Looks good on my part

2017-05-08 12:15 UTC, alexsaaf approved these changes

2017-05-11 18:21 UTC, merged