Add Implemented algorithms section
holmgr/dsa-cozy-corner pull request #8
Opened 2017-03-16 10:19 UTC by alexsaaf

Not 100% sure about how we want to format the info about the implemented algorithms but I figured it's a start.

2017-03-16 12:38 UTC, holmgr commented
Looks pretty good to me. I was however thinking more in terms of a sort of table? Where we have the name, file, time/space-complexity and type (in-place, recursive, etc.). What do you think?

2017-03-16 14:39 UTC, alexsaaf commented
Yeah, you're right. That will probably work better, especially when the number of implemented algorithms start to increase.

2017-03-17 07:13 UTC, holmgr requested changes

2017-03-17 07:13 UTC, holmgr commented on README.md
> +|  Quick sort 	| Sorts a list in place | sorting.cpp 	| O(nlogn) (O(n^2) worst case)  	|   ?	|  In place |
I think space complexity is O(n), otherwise it looks perfect!

2017-03-17 07:26 UTC, alexsaaf commented on README.md
> +|  Quick sort 	| Sorts a list in place | sorting.cpp 	| O(nlogn) (O(n^2) worst case)  	|   ?	|  In place |
Yeah you're right, adding that!

2017-03-17 07:30 UTC, holmgr approved these changes
Ready to merge :+1:

2017-03-17 07:30 UTC, merged